# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: default
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgres
type: Opaque
data:
  admin-password: {{ randAlphaNum 12 | b64enc | quote }}
