# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgres
spec:
  type: {{ .Values.service.type }}
  selector:
    app: postgres
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
