# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: Tazama
version: 1.0.0
appVersion: 1.0.0
description: This is the subchart to install all the different software systems for FRMS.
keywords:
  - apm
  - arangodb
  - arangodb-ingress
  - aws-ecr-credential
  - elasticsearch
  - grafana
  - infra-chart
  - jenkins
  - keycloak
  - kibana
  - logstash
  - nats
  - nginx-ingress-controller
  - prometheus
  - redis 
  - vault
home: https://github.com/tazama-lf/On-Prem-helm
dependencies:
  - name: jenkins
    version: 5.8.86
    repository: https://charts.jenkins.io/
    condition: tazama.jenkins.enabled
  - name: valkey
    version: 0.7.7
    repository: https://valkey.io/valkey-helm/
  - name: nats
    version: 1.3.14
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: tazama.nats.enabled
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: tazama.elasticsearch.enabled
  - name: apm-server
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: tazama.apm-server.enabled
  - name: grafana
    version: 9.4.5
    repository: https://grafana.github.io/helm-charts/
    condition: tazama.grafana.enabled
  - name: kibana
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: tazama.kibana.enabled
  - name: prometheus
    version: 27.37.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: tazama.prometheus.enabled
  - name: postgres
    version: 1.0.0
    repository: "file://customCharts/postgres"
  - name: pgadmin
    version: 1.0.0
    repository: "file://customCharts/pgadmin"
  # - name: keycloak
  #   version: 0.6.1
  #   repository: "https://registry-1.docker.io/cloudpirates/keycloak"
  #   condition: tazama.keycloak.enabled


